### ISSUE TITLE
Remove note on cross-built kernels

### ISSUE THREAD

**Issue by koppi** [machinekit/machinekit-dkms#3]
In https://github.com/machinekit-ci/rpi_linux/pull/1/commits/afaec886254c01fa2f4d79a5e122018c52bc6446 I have fixed the issue with cross built kernels and x64-64 vs. ARM executables in cross-built linux-header Debian packages.

@mhaberler please remove [the note on cross-built kernels](https://github.com/machinekit/machinekit-dkms/blame/54a58b624c09ff2ae9ca13ea47567e53b1808f19/README.md#L127-L173) in the README.md and adapt all the other kernel package Jenkins cross build scripts to make the dkms mechanism work properly with cross-built linux-header packages.

**Comment by mhaberler** [comment]
the socfpga kernel is fine wrt out-of-tree and dkms module builds.

thanks! yes, that was so-so text.
